# Power of Numpy computation


In [1]:
import numpy as np


In [2]:
#python list(without numpy)

L = range(1000)

In [3]:
print(L)

range(0, 1000)


In [4]:
%timeit [i ** 2 for i in L]

308 µs ± 14.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
#with numpy
a = np.arange(1000)
%timeit a**2

1.35 µs ± 30.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# 1-D


In [2]:
import numpy as np

a = np.array([0,1,2,3])


In [5]:
a

array([0, 1, 2, 3])

In [3]:
#print dimension
a.ndim

1

In [4]:
#shape
a.shape

(4,)

In [7]:
len(a)

4

In [ ]:
#2-D, 3-D, ---

In [9]:
b = np.array([[0,1,2,3,4], [1,2,3,4,5]])

In [10]:
b


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5]])

In [11]:
b.ndim

2

In [12]:
b.shape


(2, 5)

In [14]:
len(b)#returns the size of the first dimension

2

In [17]:
#3-d

c=np.array([[[0,1,2]], [[3,4,5]], [[6,7,8]], [[9,1,3]]])

In [18]:
c

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]],

       [[9, 1, 3]]])

In [19]:
c.ndim

3

In [36]:
#3-d
d=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

In [37]:
d


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
d.ndim

3

In [39]:
d.shape

(2, 2, 2)

In [40]:
#using arrange function
a=np.arange(10)#0...n-1

In [41]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b = np.arange(1,10,2)# start, end(exclusive), step

In [43]:
b

array([1, 3, 5, 7, 9])

In [44]:
#using linspace
c= np.linspace(0,1,6)#start, end, number of points

In [45]:
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [47]:
#common arrays
a= np.ones((2,2))

In [48]:
a


array([[1., 1.],
       [1., 1.]])

In [49]:
b=np.ones((3,3))

In [50]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
c=np.zeros((2,2))

In [52]:
c

array([[0., 0.],
       [0., 0.]])

In [53]:
d=np.zeros((3,3))

In [54]:
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
#identity matrix I(3,0)=I(3)
a=np.eye(3)

In [56]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
b=np.eye(3,2)

In [58]:
b

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [60]:
#creating array using diagonal function
a = np.diag([1,2,3,4])#create diagnonal matrix of 4*4

In [61]:
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [62]:
#extracting diagonal
b=np.diag(a)

In [63]:
b

array([1, 2, 3, 4])

In [64]:
#creating array using random (uniform distribution)
a= np.random.rand(4)

In [65]:
a

array([0.62609447, 0.72251467, 0.28578506, 0.14798725])

In [66]:
#creating array of Gaussian standard normal distribution
b = np.random.randn(4)
b

array([ 0.17374222, -0.23733262,  0.79311536,  1.49208143])

# Datatypes


In [67]:
a = np.arange(10)

In [68]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a.dtype

dtype('int64')

In [71]:
#converting int64 to float64
a = np.arange(10, dtype='float64')

In [72]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [76]:
#creating complex datatypes
a = np.array([1+2j, 2+3j])

In [77]:
a

array([1.+2.j, 2.+3.j])

In [78]:
a.dtype

dtype('complex128')

In [79]:
#creating boolean datatype
a = np.array([True, False, True])

In [80]:
a.dtype

dtype('bool')

In [82]:
print(a.dtype)

bool


In [84]:
#string array

b = np.array(['Ram','Robert', 'Rahim'])

In [85]:
b.dtype

dtype('<U6')

# Indexing and Slicing


In [ ]:
#in python indexing starts at 0



In [86]:
a = np.arange(10)

In [87]:
a[5]

5

In [88]:
a = np.array([1,3,4,6,8])

In [89]:
a[3]

6

In [90]:
#for multidimensional arrays, indexes are tuples of integers
a = np.diag([1,2,3])

In [91]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [92]:
print(a[2,2])

3


In [93]:
#assigning values and see changes in a matrix above
a[2,1]=5

In [94]:
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [95]:
#slicing

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a[1:8:2] #start:end:step


array([1, 3, 5, 7])

In [100]:
#combining assignment and slicing
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
#make changes in a 
a[5:] = 10

In [104]:
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [106]:
b=np.arange(5)
#reversing by b by step size -1
a[5:] = b[::-1]

In [107]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [108]:
#now
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [110]:
#checking whether both arrays sharing memory
np.shares_memory( a,b)

True

In [111]:
#when we modify b then a will be also modify 
b[0]=10

In [112]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [113]:
#if you dont want sharing memory then use copy function
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
b=a[::2].copy()
np.shares_memory(a,b)

False

In [116]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [117]:
#see a will not change now
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Fancy indexing

In [118]:
a = np.random.randint(0,10,10)
a

array([4, 6, 8, 8, 3, 8, 5, 6, 6, 6])

In [126]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [128]:
a[[2, 3, 2, 4, 8]]

array([20, 30, 20, 40, 80])

In [129]:
#values can be assigned
a[[4, 5]] = -100

In [130]:
a

array([   0,   10,   20,   30, -100, -100,   60,   70,   80,   90])

In [1]:
#press escape and then h for shortcuts

In [4]:
import numpy as np

In [6]:
#difference between list and array
#list can be appended but array can not be appended since it is used for vectorized operations

list = [0,1,2,3]
list

[0, 1, 2, 3]

In [7]:
list.append(4)

In [8]:
list

[0, 1, 2, 3, 4]

In [10]:
array = np.array([0,1,2,3])

In [11]:
array

array([0, 1, 2, 3])

In [12]:
#in list, you can not do listwise operations, you will get error while adding 1 in list, but not in array
list+1

TypeError: can only concatenate list (not "int") to list

In [13]:
#in array, you can do operations
array+1

array([1, 2, 3, 4])

In [15]:
#2d
#lists of list
list2= [[1,1,1], [2,2,2], [3,3,3]]
list2

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [16]:
arr2d = np.array(list2)
arr2d

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [17]:
arr2d.shape

(3, 3)

In [18]:
arr2d.ndim

2

In [19]:
type(arr2d)

numpy.ndarray

In [20]:
arr2d.dtype

dtype('int64')

In [21]:
#converting to float
arr2d = np.array(list2, dtype= 'float')
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [22]:
arr2d.dtype

dtype('float64')

In [23]:
#for detail description about documentation, you can use "shift+tab" before parenthesis and "shift+double tab" for detailed documentation


In [24]:
#convert float to int
arr2d.astype('int')

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [25]:
#covert to string
arr2d.astype("str")

array([['1.0', '1.0', '1.0'],
       ['2.0', '2.0', '2.0'],
       ['3.0', '3.0', '3.0']], dtype='<U32')

In [27]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [28]:
list

[0, 1, 2, 3, 4]

In [29]:
list.append('5')

In [30]:
list

[0, 1, 2, 3, 4, '5']

In [31]:
#converting array to list

list

[0, 1, 2, 3, 4, '5']

In [32]:
arr2list = arr2d.tolist()

In [33]:
arr2list

[[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]]

In [34]:
#array to string
arr2str = arr2d.tostring()
arr2str

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@'

# Dtype and shape


In [35]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [37]:
arr2d= arr2d.astype('float')

In [38]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [39]:
print('Shape:', arr2d.shape)

Shape: (3, 3)


In [40]:
arr2d.dtype

dtype('float64')

In [41]:
arr2d.size

9

In [42]:
arr2d.ndim

2

In [43]:
arr1d = arr2d * arr2d

In [44]:
arr1d

array([[1., 1., 1.],
       [4., 4., 4.],
       [9., 9., 9.]])

In [45]:
#extracting element
arr1d[0]

array([1., 1., 1.])

In [46]:
arr2d[0][1]#[Row][Column]

1.0

In [49]:
boolarr= arr2d>1

In [50]:
boolarr

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [51]:
#reversing order of array
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [54]:
arr2rd=arr2d[::-1,]

In [55]:
arr2rd

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

# np.nan and np.inf

In [56]:
#nan is not a number and inf is infinite

arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [58]:
#adding nan and inf to array
arr2d[0][0] = np.nan
arr2d[0][1] = np.inf
arr2d

array([[nan, inf,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [60]:
#finding nan and inf in array
np.isnan(arr2d)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [61]:
np.isinf(arr2d)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [62]:
 #finding both
missing_flag = np.isnan(arr2d)| np.isinf(arr2d)
missing_flag

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [63]:
 #replacing nan and inf with 0
 
arr2d[missing_flag]=0

In [64]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])


# statistical operations

In [65]:
#mean
arr2d.mean()

1.7777777777777777

In [66]:
#max
arr2d.max()

3.0

In [67]:
#min
arr2d.min()

0.0

In [68]:
#stdv
arr2d.std()

1.1331154474650633

In [69]:
#var
arr2d.var()

1.2839506172839505

In [70]:
#squeeze
arr2d.squeeze()

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [71]:
#cumsum=adding all elements cumulatively
arr2d.cumsum()

array([ 0.,  0.,  1.,  3.,  5.,  7., 10., 13., 16.])

In [74]:
#filtering 3x3 to 2x2
arr = arr2d[:2,:2]

In [75]:
arr

array([[0., 0.],
       [2., 2.]])

In [77]:
arr2d[1:3,1:3]

array([[2., 2.],
       [3., 3.]])


# reshaping arry

In [78]:
#not possible 
arr2d.reshape(3,4)

ValueError: cannot reshape array of size 9 into shape (3,4)

In [79]:
arr2d.reshape(1,9)#row vector

array([[0., 0., 1., 2., 2., 2., 3., 3., 3.]])

In [82]:
arr2d.reshape(9,1)#column vector

array([[0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.]])

In [83]:
#if you dont know dimension

arr2d.flatten()

array([0., 0., 1., 2., 2., 2., 3., 3., 3.])

In [84]:
#same can be done with ravel
arr2d.ravel()

array([0., 0., 1., 2., 2., 2., 3., 3., 3.])

In [86]:
 #linespace
np.linspace(1,50,2)

array([ 1., 50.])

In [87]:
np.linspace(1,50,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [88]:
#logspace
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [91]:
#random number
a=np.random.rand(1,50)#uniform distribution

In [92]:
a

array([[5.94789201e-01, 3.61978156e-01, 4.45513031e-01, 8.77868659e-01,
        6.02324389e-01, 5.68745230e-01, 8.08176123e-01, 7.73972341e-01,
        3.13689886e-01, 3.23578341e-01, 4.72365277e-01, 6.93161412e-01,
        8.82559484e-01, 1.08591376e-01, 7.74462600e-01, 1.61238692e-01,
        6.86008879e-01, 4.20611114e-05, 3.28870793e-01, 1.95421560e-01,
        6.77549306e-01, 5.07369865e-02, 9.91201052e-01, 2.31029579e-01,
        3.37394980e-01, 2.42703963e-01, 2.61082047e-01, 7.75590295e-01,
        7.84774738e-01, 3.34964270e-01, 6.79094207e-01, 3.83390369e-02,
        1.94874918e-01, 3.58190732e-01, 3.69646922e-02, 5.79187001e-01,
        8.28382055e-01, 5.12543154e-01, 5.57003915e-01, 8.03807509e-01,
        1.33360147e-01, 8.52312997e-01, 6.45124081e-01, 2.53888722e-01,
        8.70611805e-01, 2.39289365e-01, 9.41607089e-01, 5.93738635e-01,
        5.43167179e-01, 6.75073955e-01]])

In [93]:
b=np.random.randn(1,50)#Gaussian standard normal distribution
b

array([[-1.49201027, -1.00103991, -1.72065122,  0.96151855,  0.86098859,
        -0.06886967,  0.93120078,  0.89564405,  0.85088675, -0.35480411,
         1.77633953,  0.95350912, -1.34470386, -2.34466264,  0.68254485,
         1.13708079, -1.80754388,  0.4114609 ,  0.56979555,  0.20980031,
        -0.30898929, -1.51374148,  0.27102896,  0.74894733, -0.62935013,
         0.21632701, -2.20705296,  0.20260223, -0.87779549,  0.66968144,
         0.99379733, -0.42826809, -0.95409388,  1.85830025, -1.34535225,
        -0.98750432, -0.73978753, -1.77871249, -1.840637  ,  0.3381897 ,
         0.33989868,  1.0553941 ,  0.41778969,  1.91770534,  0.10011553,
        -1.4656891 , -1.42013085, -0.43884882, -0.93696339,  1.59829544]])

In [108]:
c=np.random.randint(1,50,[3,3])#integer random number in 3x3 matrix size
c

array([[44, 35, 12],
       [11, 25,  9],
       [22, 11, 39]])

In [109]:
#finding unique numbers in array
np.unique(arr2d)

array([0., 1., 2., 3.])

In [114]:
#counting unique numbers
uniques, counts = np.unique(arr2d,return_counts=True)


In [115]:
uniques

array([0., 1., 2., 3.])

In [116]:
counts

array([2, 1, 3, 3])

In [2]:
import numpy as np
arr = np.array([9,10,87,67,73,73,62])
print(arr)

[ 9 10 87 67 73 73 62]



# np.where function 

In [3]:
#finding greater than 70
index_gr70 = np.where(arr>=70)

In [4]:
print(index_gr70)

(array([2, 4, 5]),)


In [7]:
arr[index_gr70]

array([87, 73, 73])

In [8]:
arr>70

array([False, False,  True, False,  True,  True, False])

In [9]:
np.where(arr>70,"gr70","lt70")

array(['lt70', 'lt70', 'gr70', 'lt70', 'gr70', 'gr70', 'lt70'],
      dtype='<U4')

In [10]:
arr

array([ 9, 10, 87, 67, 73, 73, 62])

In [12]:
arr.max()

87

In [14]:
arr.argmax()

2

In [16]:
arr.min()


9

In [17]:
arr.argmin()

0

# read and csv file

In [32]:
#reading text file
#np.genfromtxt() or np.loadtxt()
np.genfromtxt('https://github.com/justmarkham/scikit-learn-videos/tree/master/data/Advertising.csv', dtype = 'object', delimiter = ',')


ValueError: Some errors were detected !
    Line #42 (got 2 columns instead of 1)
    Line #73 (got 2 columns instead of 1)
    Line #120 (got 3 columns instead of 1)
    Line #137 (got 6 columns instead of 1)
    Line #138 (got 3 columns instead of 1)
    Line #162 (got 4 columns instead of 1)
    Line #166 (got 2 columns instead of 1)
    Line #168 (got 2 columns instead of 1)
    Line #169 (got 2 columns instead of 1)
    Line #170 (got 2 columns instead of 1)
    Line #171 (got 2 columns instead of 1)
    Line #172 (got 2 columns instead of 1)
    Line #173 (got 2 columns instead of 1)
    Line #179 (got 2 columns instead of 1)
    Line #180 (got 2 columns instead of 1)
    Line #186 (got 2 columns instead of 1)
    Line #189 (got 2 columns instead of 1)
    Line #197 (got 4 columns instead of 1)
    Line #203 (got 2 columns instead of 1)
    Line #208 (got 2 columns instead of 1)
    Line #209 (got 2 columns instead of 1)
    Line #210 (got 2 columns instead of 1)
    Line #211 (got 2 columns instead of 1)
    Line #212 (got 2 columns instead of 1)
    Line #217 (got 2 columns instead of 1)
    Line #218 (got 2 columns instead of 1)
    Line #219 (got 2 columns instead of 1)
    Line #226 (got 2 columns instead of 1)
    Line #234 (got 4 columns instead of 1)
    Line #239 (got 2 columns instead of 1)
    Line #243 (got 2 columns instead of 1)
    Line #247 (got 2 columns instead of 1)
    Line #248 (got 2 columns instead of 1)
    Line #270 (got 2 columns instead of 1)
    Line #408 (got 6 columns instead of 1)
    Line #409 (got 3 columns instead of 1)
    Line #414 (got 6 columns instead of 1)
    Line #415 (got 3 columns instead of 1)
    Line #500 (got 3 columns instead of 1)
    Line #532 (got 6 columns instead of 1)
    Line #543 (got 6 columns instead of 1)
    Line #556 (got 6 columns instead of 1)
    Line #709 (got 3 columns instead of 1)
    Line #714 (got 3 columns instead of 1)
    Line #715 (got 8 columns instead of 1)
    Line #810 (got 2 columns instead of 1)
    Line #813 (got 2 columns instead of 1)
    Line #2487 (got 2 columns instead of 1)
    Line #2488 (got 3 columns instead of 1)
    Line #2489 (got 3 columns instead of 1)
    Line #2490 (got 3 columns instead of 1)
    Line #2491 (got 3 columns instead of 1)
    Line #2492 (got 3 columns instead of 1)
    Line #2500 (got 3 columns instead of 1)
    Line #2501 (got 3 columns instead of 1)
    Line #2502 (got 3 columns instead of 1)
    Line #2503 (got 3 columns instead of 1)
    Line #2504 (got 3 columns instead of 1)
    Line #2505 (got 3 columns instead of 1)

In [33]:
#saving datafile as csv
#np.savetxt("name.csv",dataobject, delimiter=',')

In [34]:
np.save


<function numpy.save(file, arr, allow_pickle=True, fix_imports=True)>


# concat rowwise and columnwise

In [43]:
#concatenating two arrays
arr1 = np.zeros([4,4])
arr2 = np.ones([4,4])



In [41]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.concatenate([arr1,arr2], axis = 0 )# vertical concatenate due to axis=0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
#same concatenate can be achieved by np.vstack() and np.r_
np.vstack([arr1,arr2])


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
np.r_[arr1, arr2]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
#concatentate horizontally
np.concatenate([arr1,arr2], axis = 1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [53]:
np.hstack([arr1, arr2])

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [55]:
np.c_[arr1, arr2]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

# sorting a numpy arrary

In [56]:
arr = np.random.randint(0,10, size = [10,5])

In [57]:
arr

array([[0, 9, 8, 0, 4],
       [7, 3, 8, 4, 5],
       [4, 4, 6, 3, 8],
       [6, 3, 1, 9, 7],
       [3, 1, 9, 5, 8],
       [2, 1, 7, 4, 6],
       [6, 0, 3, 5, 5],
       [2, 0, 1, 0, 9],
       [7, 4, 7, 2, 1],
       [7, 7, 2, 1, 7]])

In [59]:
np.sort(arr)#this is distorting the original data

array([[0, 0, 4, 8, 9],
       [3, 4, 5, 7, 8],
       [3, 4, 4, 6, 8],
       [1, 3, 6, 7, 9],
       [1, 3, 5, 8, 9],
       [1, 2, 4, 6, 7],
       [0, 3, 5, 5, 6],
       [0, 0, 1, 2, 9],
       [1, 2, 4, 7, 7],
       [1, 2, 7, 7, 7]])

In [60]:
#hence use this
arr[:,0]

array([0, 7, 4, 6, 3, 2, 6, 2, 7, 7])

In [63]:
sorted_index = arr[:,0].argsort()

In [64]:
arr[sorted_index]

array([[0, 9, 8, 0, 4],
       [2, 1, 7, 4, 6],
       [2, 0, 1, 0, 9],
       [3, 1, 9, 5, 8],
       [4, 4, 6, 3, 8],
       [6, 3, 1, 9, 7],
       [6, 0, 3, 5, 5],
       [7, 3, 8, 4, 5],
       [7, 4, 7, 2, 1],
       [7, 7, 2, 1, 7]])

In [65]:
arr#compare with above now

array([[0, 9, 8, 0, 4],
       [7, 3, 8, 4, 5],
       [4, 4, 6, 3, 8],
       [6, 3, 1, 9, 7],
       [3, 1, 9, 5, 8],
       [2, 1, 7, 4, 6],
       [6, 0, 3, 5, 5],
       [2, 0, 1, 0, 9],
       [7, 4, 7, 2, 1],
       [7, 7, 2, 1, 7]])

# Working with dates

In [68]:
date= np.datetime64('2020-05-20 16:32:00')

In [69]:
date

numpy.datetime64('2020-05-20T16:32:00')

In [70]:
#add 1 in date
date + 1

numpy.datetime64('2020-05-20T16:32:01')

In [71]:
oneday = np.timedelta64(1, 'D')

In [72]:
oneday+1

numpy.timedelta64(2,'D')

In [73]:
date+oneday

numpy.datetime64('2020-05-21T16:32:00')

In [74]:
oneminute = np.timedelta64(1,"m")

In [75]:
date+oneminute

numpy.datetime64('2020-05-20T16:33:00')

In [82]:
dates1 = np.arange(np.datetime64('2020-05-20'), np.datetime64('2021-05-20'))
dates1

array(['2020-05-20', '2020-05-21', '2020-05-22', '2020-05-23',
       '2020-05-24', '2020-05-25', '2020-05-26', '2020-05-27',
       '2020-05-28', '2020-05-29', '2020-05-30', '2020-05-31',
       '2020-06-01', '2020-06-02', '2020-06-03', '2020-06-04',
       '2020-06-05', '2020-06-06', '2020-06-07', '2020-06-08',
       '2020-06-09', '2020-06-10', '2020-06-11', '2020-06-12',
       '2020-06-13', '2020-06-14', '2020-06-15', '2020-06-16',
       '2020-06-17', '2020-06-18', '2020-06-19', '2020-06-20',
       '2020-06-21', '2020-06-22', '2020-06-23', '2020-06-24',
       '2020-06-25', '2020-06-26', '2020-06-27', '2020-06-28',
       '2020-06-29', '2020-06-30', '2020-07-01', '2020-07-02',
       '2020-07-03', '2020-07-04', '2020-07-05', '2020-07-06',
       '2020-07-07', '2020-07-08', '2020-07-09', '2020-07-10',
       '2020-07-11', '2020-07-12', '2020-07-13', '2020-07-14',
       '2020-07-15', '2020-07-16', '2020-07-17', '2020-07-18',
       '2020-07-19', '2020-07-20', '2020-07-21', '2020-

In [83]:
dates2 = np.arange(np.datetime64('2020-05-20'), np.datetime64('2021-05-20'),2)
dates2

array(['2020-05-20', '2020-05-22', '2020-05-24', '2020-05-26',
       '2020-05-28', '2020-05-30', '2020-06-01', '2020-06-03',
       '2020-06-05', '2020-06-07', '2020-06-09', '2020-06-11',
       '2020-06-13', '2020-06-15', '2020-06-17', '2020-06-19',
       '2020-06-21', '2020-06-23', '2020-06-25', '2020-06-27',
       '2020-06-29', '2020-07-01', '2020-07-03', '2020-07-05',
       '2020-07-07', '2020-07-09', '2020-07-11', '2020-07-13',
       '2020-07-15', '2020-07-17', '2020-07-19', '2020-07-21',
       '2020-07-23', '2020-07-25', '2020-07-27', '2020-07-29',
       '2020-07-31', '2020-08-02', '2020-08-04', '2020-08-06',
       '2020-08-08', '2020-08-10', '2020-08-12', '2020-08-14',
       '2020-08-16', '2020-08-18', '2020-08-20', '2020-08-22',
       '2020-08-24', '2020-08-26', '2020-08-28', '2020-08-30',
       '2020-09-01', '2020-09-03', '2020-09-05', '2020-09-07',
       '2020-09-09', '2020-09-11', '2020-09-13', '2020-09-15',
       '2020-09-17', '2020-09-19', '2020-09-21', '2020-

In [84]:
dates5 = np.arange(np.datetime64('2020-05-20'), np.datetime64('2021-05-20'),5)
dates5

array(['2020-05-20', '2020-05-25', '2020-05-30', '2020-06-04',
       '2020-06-09', '2020-06-14', '2020-06-19', '2020-06-24',
       '2020-06-29', '2020-07-04', '2020-07-09', '2020-07-14',
       '2020-07-19', '2020-07-24', '2020-07-29', '2020-08-03',
       '2020-08-08', '2020-08-13', '2020-08-18', '2020-08-23',
       '2020-08-28', '2020-09-02', '2020-09-07', '2020-09-12',
       '2020-09-17', '2020-09-22', '2020-09-27', '2020-10-02',
       '2020-10-07', '2020-10-12', '2020-10-17', '2020-10-22',
       '2020-10-27', '2020-11-01', '2020-11-06', '2020-11-11',
       '2020-11-16', '2020-11-21', '2020-11-26', '2020-12-01',
       '2020-12-06', '2020-12-11', '2020-12-16', '2020-12-21',
       '2020-12-26', '2020-12-31', '2021-01-05', '2021-01-10',
       '2021-01-15', '2021-01-20', '2021-01-25', '2021-01-30',
       '2021-02-04', '2021-02-09', '2021-02-14', '2021-02-19',
       '2021-02-24', '2021-03-01', '2021-03-06', '2021-03-11',
       '2021-03-16', '2021-03-21', '2021-03-26', '2021-

# Numpy advanced function

In [85]:
#vectorize function


In [88]:
def foo(x):
    if x%2 ==1:
        return x**2
    else:
        return x/2

foo(10)


5.0

In [89]:
foo(11)

121

In [90]:
foo(12)

6.0

In [91]:
foo(13)

169

In [92]:
foo(14)

7.0

In [94]:
#vectorize
foo_v = np.vectorize(foo)

In [95]:
arr

array([[0, 9, 8, 0, 4],
       [7, 3, 8, 4, 5],
       [4, 4, 6, 3, 8],
       [6, 3, 1, 9, 7],
       [3, 1, 9, 5, 8],
       [2, 1, 7, 4, 6],
       [6, 0, 3, 5, 5],
       [2, 0, 1, 0, 9],
       [7, 4, 7, 2, 1],
       [7, 7, 2, 1, 7]])

In [96]:
foo_v(arr)

array([[ 0., 81.,  4.,  0.,  2.],
       [49.,  9.,  4.,  2., 25.],
       [ 2.,  2.,  3.,  9.,  4.],
       [ 3.,  9.,  1., 81., 49.],
       [ 9.,  1., 81., 25.,  4.],
       [ 1.,  1., 49.,  2.,  3.],
       [ 3.,  0.,  9., 25., 25.],
       [ 1.,  0.,  1.,  0., 81.],
       [49.,  2., 49.,  1.,  1.],
       [49., 49.,  1.,  1., 49.]])